### ISSUE TITLE
Use views in wh_learn?

### ISSUE THREAD

**Issue by dmbates** [MegamindHenry/JudiLing.jl#40]
I notice that the `wh_learn` has some matrix multiplications using `mul!` inside a loop on epochs and that the arguments are slices of matrices.  It may be more efficient to use views as they do not require copying.  So an expression like
```
      mul!(pred, X[i:i, :], W)
```
involves copying the i'th row of `X` but
```
      mul!(pred, view(X, i:i, :), W)
```
doesn't.

**Comment by MegamindHenry** [comment]
Thank you Prof. Bates! It is done!
