### ISSUE TITLE
Bug in progress bar in wh.jl

### ISSUE THREAD

**Issue by MariaHei** [MegamindHenry/JudiLing.jl#46]
[The length of the Progress Bar in wh.jl](https://github.com/MegamindHenry/JudiLing.jl/blob/8558d3ef649d9088893c4300b0c55c6d4db500d4/src/wh.jl#L32)
`verbose && begin pb = Progress(size(X,1)*n_epochs) end`
currently doesn't respond to the two for-loops if `learn_seq` is not as long as `size(X,1)`.
I think it should be `verbose && begin pb = Progress(size(learn_seq,1)*n_epochs) end`.

**Comment by MegamindHenry** [comment]
Thank you Maria. Now it is fixed.
